name: Deploy QA

on:
  push:
    branches:
      - new-qa
      - qa
      - qa
    tags:
      - '**.*.*-rc.*'

jobs:
  build-qa:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::650251729525:role/GithubBackendDeployRole
          aws-region: us-west-2

      - name: Get Chainguard credentials
        id: chainguard-creds
        run: |
          CREDS=$(aws secretsmanager get-secret-value --secret-id global/Chainguard/Credentials --query SecretString --output text)
          USERNAME=$(echo $CREDS | jq -r '.username')
          PASSWORD=$(echo $CREDS | jq -r '.password')
          echo "::add-mask::$USERNAME"
          echo "::add-mask::$PASSWORD"
          echo "username=$USERNAME" >> $GITHUB_ENV
          echo "password=$PASSWORD" >> $GITHUB_ENV

      - name: Login to Chainguard registry
        uses: docker/login-action@v3
        with:
          registry: cgr.dev
          username: ${{ env.username }}
          password: ${{ env.password }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/bff-backend
          tags: |
            type=raw,value=latest
            type=sha,format=short

      - name: Docker cache layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Create cache directory if it doesn't exist
      - name: Ensure cache directory exists
        run: mkdir -p /tmp/.buildx-cache

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          platforms: linux/amd64
          build-args: |
            NODE_ENV=production

      # Temp cache workaround for buildx
      # https://github.com/docker/build-push-action/issues/252
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Notify Google Chat
        if: ${{ always() }} # Use always to ensure that the notification is also send on failure of former steps
        uses: SimonScholz/google-chat-action@main
        with:
          webhookUrl: "https://chat.googleapis.com/v1/spaces/AAAANb1C8q4/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=-MC6qIuIlqv_-HFkg3EN2TQGy5MrQjF-I-UOyYkz_bA"
          jobStatus: "${{ job.status }}"

  deploy-qa-backend:
    runs-on: ubuntu-latest
    needs: build-qa
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::650251729525:role/GithubBackendDeployRole
          aws-region: us-west-2

      - name: Set GitHub tag or ref as VERSION
        id: set-version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
              echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
              echo "VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV
          fi

      - name: Set ENVIRONMENT
        id: set-environment
        run: |
          echo "ENVIRONMENT=qa" >> $GITHUB_ENV

      # Prepare task definitions for parallel deployment
      - name: Fetch current ECS task definition
        id: get-task-def
        run: |
          echo "Fetching current Bff task definition..."
          aws ecs describe-task-definition --task-definition Bff --query "taskDefinition" > task-definition.json

      - name: Prepare Bff task definition
        id: prepare-bff-task-def
        env:
          VERSION: ${{ env.VERSION }}
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
        run: |
          echo "Preparing Bff task definition..."

          jq 'del(
              .taskDefinitionArn,
              .revision,
              .status,
              .requiresAttributes,
              .compatibilities,
              .registeredAt,
              .registeredBy
          )' task-definition.json > new-task-definition.json

          jq --arg VERSION "$VERSION" --arg ENVIRONMENT "$ENVIRONMENT" \
              '.containerDefinitions[0].environment += [{"name":"VERSION","value":$VERSION},{"name":"ENVIRONMENT","value":$ENVIRONMENT}]' \
              new-task-definition.json > final-task-def.json
              
      - name: Upload Bff task definition
        uses: actions/upload-artifact@v4
        with:
          name: bff-task-definition
          path: final-task-def.json
          retention-days: 1

      - name: Prepare BffPrivate task definition
        id: prepare-bff-private-task-def
        env:
          VERSION: ${{ env.VERSION }}
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
        run: |
          echo "Fetching current BffPrivate task definition..."
          aws ecs describe-task-definition --task-definition BffPrivate --query "taskDefinition" > task-definition-private.json
          
          echo "Preparing BffPrivate task definition..."
          jq 'del(
              .taskDefinitionArn,
              .revision,
              .status,
              .requiresAttributes,
              .compatibilities,
              .registeredAt,
              .registeredBy
          )' task-definition-private.json > new-task-definition-private.json

          jq --arg VERSION "$VERSION" --arg ENVIRONMENT "$ENVIRONMENT" \
              '.containerDefinitions[0].environment += [{"name":"VERSION","value":$VERSION},{"name":"ENVIRONMENT","value":$ENVIRONMENT}]' \
              new-task-definition-private.json > final-task-def-private.json
              
      - name: Upload BffPrivate task definition
        uses: actions/upload-artifact@v4
        with:
          name: bff-private-task-definition
          path: final-task-def-private.json
          retention-days: 1

  # Run deployments in parallel
  deploy-bff-service:
    needs: deploy-qa-backend
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::650251729525:role/GithubBackendDeployRole
          aws-region: us-west-2

      - name: Download task definition artifact
        uses: actions/download-artifact@v4
        with:
          name: bff-task-definition
          path: ./

      - name: Deploy BFF service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: final-task-def.json
          service: BffService
          cluster: bff-backend-cluster-primary
          wait-for-service-stability: true

  deploy-bff-private-service:
    needs: deploy-qa-backend
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::650251729525:role/GithubBackendDeployRole
          aws-region: us-west-2

      - name: Download task definition artifact
        uses: actions/download-artifact@v4
        with:
          name: bff-private-task-definition
          path: ./

      - name: Deploy BFF Private service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: final-task-def-private.json
          service: BffServicePrivate
          cluster: bff-backend-cluster-primary
          wait-for-service-stability: true

  send-notification:
    needs: [deploy-bff-service, deploy-bff-private-service]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Notify Google Chat
        uses: SimonScholz/google-chat-action@main
        with:
          webhookUrl: "https://chat.googleapis.com/v1/spaces/AAAANb1C8q4/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=-MC6qIuIlqv_-HFkg3EN2TQGy5MrQjF-I-UOyYkz_bA"
          jobStatus: "${{ job.status }}"